### ISSUE TITLE
TV3 Play error on Android

### ISSUE THREAD

**Issue by Oyuret** [anorm/plugin.video.tv3play.dk#1]
The addon (current version 3.0.1) does not boot on the Android version of Kodi 15.2.

Kodi logs shows the following:

```
ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) 
  - Error getting plugin://plugin.video.tv3play.dk/
    ValueError: zero length field name in format xbmc.log("{}{}".format(sys.argv[0], sys.argv[2]))

File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.tv3play.dk/addon.py", line 191, in <module>
```

**Comment by anorm** [comment]
I don't have an Android system to test on. @Oyuret can you check if this fixes to issue? Download from here: https://github.com/anorm/plugin.video.tv3play.dk/archive/bugfix/1.zip

**Comment by Oyuret** [comment]
@anorm The bugfix fixes the issue. Thank you for your work.

**Comment by anorm** [comment]
Merged to master. Will be in 3.0.2
