### ISSUE TITLE
TV3 play - No longer working

### ISSUE THREAD

**Issue by msj33** [anorm/plugin.video.tv3play.dk#7]
Hi @anorm 

TV3 play addon is no longer working - The streams does not start any longer(encryption error?)

Get this in the logs:

16:20:11.594 T:8484   ERROR: CCurlFile::Stat - Failed: SSL peer certificate or SSH remote key was not OK(51) for https://cdn.playapi.mtgx.tv/imagecache/original/cloud/content-images/channels/bugs/9500.png

Debug only shows this:
16:26:19.171 T:11592   DEBUG: CGUIWindowVideoBase::OnPlayMedia plugin://plugin.video.tv3play.dk/?action=playVideo&playVideo=http%3A%2F%2Fiphone.cdn.viasat.tv%2Fiphone%2F004%2F00478%2FS47800_2boliger1pris_kgmjhckiqkdxl96p_iphone.m3u8&region=dk&title=2+Boliger%2C+1+Pris+S01E01
16:26:19.171 T:11592 WARNING: Playlist Player: ListItem type must be audio or video, use ListItem::setInfo to specify!

Are you still active developing on this addon?

**Comment by msj33** [comment]
If you can get the addon working again, please provide a PR for getting the upstream working.

If you want to be active contributer on the original source, please also reach out.

Then we can consolidate the active development around as few repo as possible, thanks

**Comment by anorm** [comment]
I have very little time to look at it and I'm not using the plugin myself but I might be able to sit down and try to fix it in the near future.
